version: '2.1'

services:
  hacker:
    build: ./hacker
    container_name: hacker
    ports:
    - "443:443"
    - "22:2222"
    hostname: hacker
    volumes:
    - ~/.msf4:/root/.msf4
    - /tmp/msf:/tmp/data
    - ./metasploit:/tmp/msf
    extra_hosts:
    - "gateway:172.16.200.11"
    - "sys3:172.16.201.12"
    - "sys4:172.16.201.13"
    
    networks:
      attack-net:
        ipv4_address: 172.16.200.10
      target-net:
        ipv4_address: 172.16.201.10        
  gateway:
    build: ./gateway
    container_name: gateway
    hostname: gateway
    extra_hosts:
    - "hacker:172.16.200.10"
    - "sys3:172.16.201.12"
    - "sys4:172.16.201.13"
    networks:
      attack-net:
        ipv4_address: 172.16.200.11
      target-net:
        ipv4_address: 172.16.201.11

  sys3:
    image: wpscanteam/vulnerablewordpress

    container_name: sys3
    hostname: sys3
    extra_hosts:
    - "gateway:172.16.201.11"
    - "sys4:172.16.201.13" 
    ports:
    - "80:80"
    - "3306:3306"       
    networks:
      target-net:
        ipv4_address: 172.16.201.12
  sys4:
    build: ./sys4
    container_name: sys4
    hostname: sys4
    extra_hosts:
    - "gateway:172.16.201.11"
    - "sys3:172.16.201.12"
    networks:
      target-net:
        ipv4_address: 172.16.201.13
  

networks:
  attack-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.200.0/24
        gateway: 172.16.200.2
  target-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.201.0/24
        gateway: 172.16.201.2
